name: demo
on:
  workflow_dispatch:
  push:
    branches:
      - 'demo**'
    tags-ignore:
      - '**'

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          npm ci
          npm run build
      - name: full options
        uses: ./
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          content: "testing"
          username: Build
          avatar_url: "https://github.com/dothq.png"
        with:
          nodetail: true
          title: "We did it!"
          color: 0xff91a4
      - name: markdown
        uses: ./
        with:
          webhook: ${{ secrets.DISCORD_DEMO }}
          nodetail: true
          title: New version of `software` is ready!
          description: |
            Version `1.2.3-alpha`
            Click [here](https://github.com/sarisia/actions-status-discord) to download!
