name: Release
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm test
      - run: npm run release
      - name: Release
        run: |
          git config --global user.name "4IP"
          git config --global user.email "${{ secrets.EMAIL }}"
          git status
          git add lib node_modules
          git commit -m "✨ Add built code"
          git push origin master
